spring:
  application:
    name: student_management

  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
    password: 12344321
    driver-class-name: com.mysql.cj.jdbc.Driver